spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: gemma2-9b-it
mcp:
  servers:
    server1:
      url: http://localhost:8081